### ISSUE TITLE
minibatch_size 

### ISSUE THREAD

**Issue by elisim** [leaf-ai/rio-paper#2]
https://github.com/leaf-ai/rio-paper/blob/542e9e7a746e3e277a5b5b2c0f3d7935df148568/main_experiments_RIO_variants.py#L154

Hey, is it on purpose? 
Because your discard the 
```python
minibatch_size_list = [246,614,614,1202,824,1279,3918,7654,36584,17010,42800,463715]
```

Thanks

**Comment by VsonicV** [comment]
Hi @elisim ,
     Sorry for the late reply. Yes, for the current implementation, RIO is using L-BFGS-B optimizer instead of a minibatch-based optimizer (e.g., SGD), so the `minibatch_size` and `minibatch_size_list` are not used during the RIO training at all. We have run some preliminary tests by using SGD with different minibatch sizes, and in most cases RIO is able to converge to a better-performing point but with much longer computation time. We have plans to include minibatch-based optimizer in the next version, and these two variables will be active by then. For now, they should be discarded. Sorry for the confusion! Hope it clarifies you concerns!

Best Regards,
Xin Qiu

**Comment by elisim** [comment]
Thanks
